version: '3'

services:
  redis:
    image: "redis:alpine"
    restart: always
  nginx:
    restart: always
    image: nginx:latest
    ports:
      - "8000:8000"
    volumes:
      - ./Docker/nginx/conf.d:/etc/nginx/conf.d
      - ./gelweb/gelweb/static_files:/static
    depends_on:
      - web
      - redis
  web:
    image: gel2mdt_web
    restart: always
    build:
      context: .
    command: bash -c ". /root/gel2mdt/Docker/startup_script.sh && cd /root/gel2mdt/gelweb && gunicorn gelweb.wsgi -b 0.0.0.0:8000"
    volumes:
      - .:/root/gel2mdt/
      - ~/.vep:/root/.vep
      - ~/gel2mdt_resources:/root/gel2mdt_cache
    env_file:
      - /etc/gel2mdt/credentials
    depends_on:
      - db
      - redis
  jupyter:
    image: gel2mdt_jupyter
    build: .
    restart: always
    build:
      context: .
    command: bash -c ". /root/gel2mdt/Docker/startup_script.sh && jupyter notebook --generate-config -y && cd /root/gel2mdt/gelweb && python manage.py shell_plus --notebook"
    volumes:
      - .:/root/gel2mdt/
    env_file:
      - /etc/gel2mdt/credentials
    ports:
      - "8891:8888"
    depends_on:
      - db
      - redis
      - web
  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=gel2mdt_db
      - MYSQL_USER=paddy
    env_file:
      - /etc/gel2mdt/credentials
    volumes:
      - ~/gel2mdt_resources/gel2mdt_db:/var/lib/mysql
#  db:
#    image: postgres:10
#    restart: always
#    environment:
#      - POSTGRES_DB=gel2mdt_db
#      - POSTGRES_USER=paddy
#    env_file:
#      - /etc/gel2mdt/credentials
#    volumes:
#      - ~/gel2mdt_resources/gel2mdt_db:/var/lib/postgresql/data
  celery:
    build: .
    restart: always
    image: gel2mdt_celery
    command: bash -c ". /root/gel2mdt/Docker/startup_script.sh && cd /root/gel2mdt/gelweb && celery -A gelweb worker -l info"
    env_file:
      - /etc/gel2mdt/credentials
    volumes:
      - .:/root/gel2mdt/
      - ~/.vep:/root/.vep
      - ~/gel2mdt_resources:/root/gel2mdt_cache
    depends_on:
      - db
      - redis
  celery-beat:
    build: .
    image: gel2mdt_celery-beat
    restart: always
    command: bash -c ". /root/gel2mdt/Docker/startup_script.sh && cd /root/gel2mdt/gelweb && rm -f celerybeat.pid && celery -A gelweb beat -l info"
    env_file:
      - /etc/gel2mdt/credentials
    volumes:
      - .:/root/gel2mdt/
      - ~/.vep:/root/.vep
      - ~/gel2mdt_resources:/root/gel2mdt_cache
    depends_on:
      - db
      - redis
  flower:
    build: .
    image: gel2mdt_flower
    restart: always
    command: bash -c "cd /root/gel2mdt/gelweb && celery flower -A gelweb --broker=redis://redis:6379 --port=5550"
    ports:
      - "5550:5550"
    depends_on:
      - db
      - redis
      - celery
      - celery-beat
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    volumes:
      - /sessions
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - db



