version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8000:8000"
    volumes:
      - ./Docker/nginx/conf.d:/etc/nginx/conf.d
      - ./gelweb/gel2mdt/static:/static
    depends_on:
      - web
  web:
    image: gel2mdt_web
    build:
      context: .
    command: bash -c ". /code/Docker/startup_script.sh && cd /root/gel2mdt/gelweb && gunicorn gelweb.wsgi -b 0.0.0.0:8000"
    #restart: always
    volumes:
      - .:/code
      - /media/sf_shared_resources:/root/reference
      - /media/sf_shared_resources/.vep:/root/.vep
      - /home/phil/Documents/gel2mdt_resources:/root/gel2mdt_cache
    depends_on:
      - db
  db:
    image: postgres:10
    restart: always
    environment:
      - POSTGRES_USER=gel2mdtuser
      - POSTGRES_PASSWORD=gel2mdtpassword
      - POSTGRES_DB=gel2mdt_db
    volumes:
      - /home/phil/Documents/gel2mdt_resources/gel2mdt_db:/var/lib/postgresql/data




