# Generated by Django 2.0.1 on 2018-04-06 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gel2mdt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proband',
            name='gmc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
