# Generated by Django 2.0.1 on 2018-04-06 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gel2mdt', '0002_auto_20180406_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='interpretationreportfamilypanel',
            name='custom',
            field=models.BooleanField(default=True),
        ),
    ]
