# Generated by Django 2.0.1 on 2018-04-10 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gel2mdt', '0004_auto_20180406_0746'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listupdate',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='listupdate',
            table='ListUpdate',
        ),
    ]
