# Generated by Django 2.0.1 on 2018-04-10 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gel2mdt', '0005_auto_20180410_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proband',
            name='gmc',
            field=models.CharField(blank=True, choices=[('GOSH', 'GOSH'), ('MEH', 'MEH'), ('NHNN', 'NHNN'), ('RRV', 'RRV'), ('HHP', 'HHP'), ('RAL', 'RAL'), ('LNWH', 'LNWH'), ('UCLH', 'UCLH'), ('RNOH', 'RNOH'), ('WLGMC', 'WLGMC'), ('R1H', 'R1H'), ('RP4', 'RP4'), ('RAN', 'RAN'), ('RRV', 'RRV'), ('RT3', 'RT3'), ('Unknown', 'Unknown')], default='Unknown', max_length=255, null=True),
        ),
    ]
