# Generated by Django 2.0.1 on 2018-04-11 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gel2mdt', '0006_auto_20180410_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='mdt',
            name='sample_type',
            field=models.CharField(choices=[('cancer', 'cancer'), ('raredisease', 'raredisease')], default='raredisease', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proband',
            name='gmc',
            field=models.CharField(blank=True, choices=[('GOSH', 'GOSH'), ('MEH', 'MEH'), ('NHNN', 'NHNN'), ('RRV', 'RRV'), ('HHP', 'HHP'), ('RAL_neuro', 'RAL_neuro'), ('RAL_renal', 'RAL_renal'), ('LNWH', 'LNWH'), ('UCLH', 'UCLH'), ('RNOH', 'RNOH'), ('WLGMC', 'WLGMC'), ('BHNT', 'BHNT'), ('R1H', 'R1H'), ('RP4', 'RP4'), ('RAN', 'RAN'), ('RRV', 'RRV'), ('RT3', 'RT3'), ('Unknown', 'Unknown')], default='Unknown', max_length=255, null=True),
        ),
    ]
