# Generated by Django 2.0.1 on 2018-04-11 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gel2mdt', '0007_auto_20180411_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='interpretationreportfamily',
            name='gel_sample_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
